#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.Forms.ControlGallery.Android.Resource", IsApplication=true)]

namespace Xamarin.Forms.ControlGallery.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int enter_from_left = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int enter_from_right = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int exit_to_left = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int exit_to_right = 2130771971;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int cellback = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int cellback2 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int custom_theme_color = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int primary_dark = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030009
			public const int bank = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int bell = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int books = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int booksflyout = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int button_add = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int calculator = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int card = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int cardBackground = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int cartman = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int coffee = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int coffee2 = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int cover1 = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int cover1small = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int crimson = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int crimsonsmall = 2130903063;
			
			// aapt resource value: 0x7F030000
			public const int CustomSelector = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int CustomSelector2 = 2130903041;
			
			// aapt resource value: 0x7F030018
			public const int error = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int film = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int filmflyout = 2130903066;
			
			// aapt resource value: 0x7F030002
			public const int FlowerBuds = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Fruits = 2130903043;
			
			// aapt resource value: 0x7F03001B
			public const int games = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int gamesflyout = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int gear = 2130903069;
			
			// aapt resource value: 0x7F030004
			public const int GifOne = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int GifTwo = 2130903045;
			
			// aapt resource value: 0x7F03001E
			public const int grid = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int headphone = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int headphoneflyout = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int heart = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int home = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int homeflyout = 2130903075;
			
			// aapt resource value: 0x7F030006
			public const int Icon = 2130903046;
			
			// aapt resource value: 0x7F030024
			public const int icon_bookmark = 2130903076;
			
			// aapt resource value: 0x7F030025
			public const int icon_search = 2130903077;
			
			// aapt resource value: 0x7F030026
			public const int invalidimage = 2130903078;
			
			// aapt resource value: 0x7F030027
			public const int jet = 2130903079;
			
			// aapt resource value: 0x7F030007
			public const int Legumes = 2130903047;
			
			// aapt resource value: 0x7F030028
			public const int loop = 2130903080;
			
			// aapt resource value: 0x7F030029
			public const int menuIcon = 2130903081;
			
			// aapt resource value: 0x7F03002A
			public const int mic = 2130903082;
			
			// aapt resource value: 0x7F03002B
			public const int newspaper = 2130903083;
			
			// aapt resource value: 0x7F03002C
			public const int newspaperflyout = 2130903084;
			
			// aapt resource value: 0x7F03002D
			public const int oasis = 2130903085;
			
			// aapt resource value: 0x7F03002E
			public const int oasissmall = 2130903086;
			
			// aapt resource value: 0x7F03002F
			public const int person = 2130903087;
			
			// aapt resource value: 0x7F030030
			public const int photo = 2130903088;
			
			// aapt resource value: 0x7F030031
			public const int rb_checked = 2130903089;
			
			// aapt resource value: 0x7F030032
			public const int rb_unchecked = 2130903090;
			
			// aapt resource value: 0x7F030033
			public const int red_button = 2130903091;
			
			// aapt resource value: 0x7F030034
			public const int seth = 2130903092;
			
			// aapt resource value: 0x7F030035
			public const int star = 2130903093;
			
			// aapt resource value: 0x7F030036
			public const int synchronize = 2130903094;
			
			// aapt resource value: 0x7F030037
			public const int synchronize_disabled = 2130903095;
			
			// aapt resource value: 0x7F030038
			public const int synchronize_enabled = 2130903096;
			
			// aapt resource value: 0x7F030039
			public const int test = 2130903097;
			
			// aapt resource value: 0x7F03003A
			public const int toolbar_close = 2130903098;
			
			// aapt resource value: 0x7F030008
			public const int Vegetables = 2130903048;
			
			// aapt resource value: 0x7F03003B
			public const int xamarinlogo = 2130903099;
			
			// aapt resource value: 0x7F03003C
			public const int xamarinstore = 2130903100;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040004
			public const int coffee = 2130968580;
			
			// aapt resource value: 0x7F040000
			public const int Image = 2130968576;
			
			// aapt resource value: 0x7F040005
			public const int sliding_tabs = 2130968581;
			
			// aapt resource value: 0x7F040001
			public const int Text = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Text1 = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int Text2 = 2130968579;
			
			// aapt resource value: 0x7F040006
			public const int toolbar = 2130968582;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int Layout38989 = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int NativeAndroidCell = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int NativeAndroidListViewCell = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int Tabbar = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int Toolbar = 2131034116;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int btnMDPAutomationID_close = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int btnMDPAutomationID_open = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppCompatDialogStyle = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int DayNightDialogStyle = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int FormsTheme = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int MyTheme = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int MyTheme_Base = 2131165188;
			
			// aapt resource value: 0x7F070006
			public const int red_button_style = 2131165190;
			
			// aapt resource value: 0x7F070005
			public const int TestStyle = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
